name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        USERNAME: ${{ secrets.USERNAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        sudo su
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        sudo su

        REPO_URL="https://${USERNAME}:${ACCESS_TOKEN}@github.com/Cannoo082/team-bull.git"
        BRANCH="main"
        REPO_DIR="/var/www/team-bull"
        cd ${REPO_DIR}
        echo "Current directory: $(pwd)
        git pull ${REPO_URL}
        echo ${REPO_URL}

        sudo chown -R $USER:$USER $REPO_DIR
        sudo chmod -R 755 $REPO_DIR

        cd "$REPO_DIR"
        npm install
        npm run build
        '
