name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete --exclude 'node_modules'
        path: ./*
        remote_path: /var/www/team-bull/
        remote_host: ec2-23-23-23-113.compute-1.amazonaws.com
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Post-deployment setup
      run: |
        ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-23-23-23-113.compute-1.amazonaws.com << EOF
          sudo su
          cd /var/www/team-bull
          npm i
        EOF
