name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      run: |
        sudo su
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la ~

        REPO_URL="https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/Cannoo082/team-bull.git"
        BRANCH="main"
        REPO_DIR="/var/www/team-bull"

        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          # Update the remote origin URL to include authentication
          git remote set-url origin "$REPO_URL"
          git pull origin "$BRANCH"
        else
          git clone "$REPO_URL" "$REPO_DIR"
          cd "$REPO_DIR"
        fi

        sudo chown -R $USER:$USER $REPO_DIR
        sudo chmod -R 755 $REPO_DIR

        cd "$REPO_DIR"
        npm install
        npm run build
        '
