name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Deploy with rsync as sudo
      run: |
        rsync -avzr --delete --exclude 'node_modules' -e "ssh -i '${{ secrets.SSH_PRIVATE_KEY }}'" ./ ubuntu@ec2-23-23-23-113.compute-1.amazonaws.com:/tmp/deploy
        ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-23-23-23-113.compute-1.amazonaws.com << EOF
          sudo rsync -avzr --delete /tmp/deploy/ /var/www/team-bull/
          sudo rm -rf /tmp/deploy
        EOF

    - name: Post-deployment setup
      run: |
        ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@ec2-23-23-23-113.compute-1.amazonaws.com << EOF
          sudo su
          cd /var/www/team-bull
          npm i
        EOF
